[package]
  cjc-version = "1.0.5"
  name = "cangjie_xml"
  description = "CangjieXML — pure-Cangjie libxml2-class XML toolkit."
  version = "0.1.0"
  target-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
